version: "3.8"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8001
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
      - HOST=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
